### ISSUE TITLE
RNChat react-native run-android crash

### ISSUE THREAD

**Issue by vkkan** [ConnectyCube/connectycube-js-samples#40]
Environment
 React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 181.70 MB / 15.58 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 4.6.1 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 21, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 24.0.2, 25.0.0, 25.0.2, 26.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Android TV Intel x86 Atom, android-26 | China version of Android Wear Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

What was done: 
yarn install
react-native run-android 

App crashes 

/com.samplechatrn E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.samplechatrn, PID: 10249
    java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY
        at android.util.JsonReader.nextString(JsonReader.java:408)
        at com.facebook.react.devsupport.BundleDeltaClient$BundleDeltaJavaClient.processDelta(BundleDeltaClient.java:103)
        at com.facebook.react.devsupport.BundleDeltaClient.processDelta(BundleDeltaClient.java:71)
        at com.facebook.react.devsupport.BundleDownloader.processBundleResult(BundleDownloader.java:314)
        at com.facebook.react.devsupport.BundleDownloader.access$200(BundleDownloader.java:37)
        at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:174)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
06-03 12:17:14.733 10249-10282/com.samplechatrn E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f7f529560
06-03 12:17:14.811 10249-10282/com.samplechatrn E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f7f528f20

**Comment by vkkan** [comment]
After closing the metro bundler and re run fixed the issue.
