### ISSUE TITLE
Unable to resolve "@xmpp/client-core"

### ISSUE THREAD

**Issue by zek** [ConnectyCube/connectycube-js-samples#8]
I followed the manual in https://developers.connectycube.com/js/react-native

but I got this error

Unable to resolve "@xmpp/client-core" from "node_modules/connectycube-reactnative/xmpp.js/packages/client/index.js"

**Comment by zek** [comment]
Also as I notice make command fails.
~~~
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:174:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:167:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:160:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:174:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:174:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:167:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:160:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:174:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/zack/.node-gyp/10.11.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
4 warnings and 1 error generated.
make[1]: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
make[1]: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! commandgyp  \"/usr/local/Cellar/node/10.11.0/bin/node\" \"/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64\"
ERR! Systemgyp Darwin 17.5.0
 ERR! cwd /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents
gyp ERR!gyp  node -vERR! v10.11.0
 commandgyp  \"/usr/local/Cellar/node/10.11.0/bin/node\" \"/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64\"
ERR! gypnode-gyp -v v3.6.2
 ERR!gyp  ERR!cwd  /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents
not ok
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.11.0/bin/node /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/10.11.0/bin/node\" \"/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents
node-pre-gyp ERR! node -v v10.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/10.11.0/bin/node /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents/lib/binding/Release/node-success Saved lockfile.
~~~

**Comment by zek** [comment]
When I checked there is no such a file in
/node_modules/connectycube-reactnative/xmpp.js/node_modules/fsevents

**Comment by DaveLombardo** [comment]
thanks, 
I see the same issue with v10.11.0

but it works great with latest v9.11.2

Not sure what is going ok, let us check

Meanwhile, is it okay for you to switch temporary to v9.11.2? 
It's easy to do with `n`:   `n 9.11.2`

**Comment by DaveLombardo** [comment]
Seems a known issue with **fsevents** under Node10

https://github.com/strongloop/fsevents/issues/229

**Comment by zek** [comment]
I am able to compile it. Thank you :)

But still I couldnt make it work. I have no idea whats wrong.

[16:37:17] Unable to resolve "@xmpp/client-core" from "node_modules/connectycube-reactnative/xmpp.js/packages/client/index.js"
[16:37:17] Failed building JavaScript bundle.

**Comment by DaveLombardo** [comment]
Did you follow all the steps from https://developers.connectycube.com/js/react-native?id=connect-sdk
(2.Apply the pre-setup steps for a internal dependency – xmpp.js lib) ?

**Comment by zek** [comment]
Yes I did follow whats written there. I will try it again from scratch.

**Comment by zek** [comment]
After that I got the error below and and installed ansi-styles.
Run the app without importing "ConnectyCube", it works.
But when I import it gives the error above.

~~~
[16:44:35] /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/chalk/index.js:66
[16:44:35] ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
[16:44:35]                                                                           ^
[16:44:35]
[16:44:35] TypeError: Cannot read property 'close' of undefined
[16:44:35]     at Object.<anonymous> (/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/chalk/index.js:66:75)
[16:44:35]     at Module._compile (internal/modules/cjs/loader.js:654:30)
[16:44:35]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
[16:44:35]     at Module.load (internal/modules/cjs/loader.js:566:32)
[16:44:35]     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
[16:44:35]     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
[16:44:35]     at Module.require (internal/modules/cjs/loader.js:598:17)
[16:44:35]     at require (internal/modules/cjs/helpers.js:11:18)
[16:44:35]     at Object.<anonymous> (/Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/react-native/local-cli/server/checkNodeVersion.js:9:13)
[16:44:35]     at Module._compile (internal/modules/cjs/loader.js:654:30)
[16:44:35] Metro Bundler process exited with code 1
~~~

**Comment by zek** [comment]
Maybe I should run `npm install` ?

Make runs successfully but doesnt create node_modules folder to be copied.

~~~
node packages/xmpp.js/script.js
yarn
yarn install v1.10.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > babelify@8.0.0" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning "workspace-aggregator-19e1d7c1-c46b-4ffe-bcb8-d434e2495db7 > @xmpp/console > bootstrap@4.1.0" has unmet peer dependency "popper.js@^1.14.0".
[5/5] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 49.04s.
lerna bootstrap
lerna notice cli v3.4.1
lerna WARN project Deprecated key "commands" found in lerna.json
lerna WARN project Please rename "commands" => "command"
lerna WARN project Deprecated key "command.publish.ignore" found in lerna.json
lerna WARN project Please rename "command.publish.ignore" => "command.publish.ignoreChanges"
lerna info bootstrap root only
yarn install v1.10.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.67s.
cd packages/xmpp.js/ && yarn run prepublish
yarn run v1.10.1
$ node script.js
✨  Done in 0.17s.
~~~

**Comment by DaveLombardo** [comment]
Actually when you call the `make`command inside `xmpp.js` dir then it does `npm install` as well

**Comment by DaveLombardo** [comment]
2 questions:
1) what version of RN you use?
2) how you created your RN project?

**Comment by zek** [comment]
Just followed the instruction in here:
https://facebook.github.io/react-native/docs/getting-started.html
React works correctly actually.
React Version: 0.55.4

**Comment by DaveLombardo** [comment]
let me quickly follow these steps at my side and re-check

**Comment by zek** [comment]
> Actually when you call the `make`command inside `xmpp.js` dir then it does `npm install` as well

Actually after that command there is no such a directory node_modules. 

After make, I run "npm install" and 'node_modules' directory is created. 
But again I get ansi-styles error.  Installing it but then as I see it just removes everything we copied
~~~
npm install ansi-styles --save
npm WARN rm not removing /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/.bin/jsesc as it wasn't installed by /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/jsesc
npm WARN rm not removing /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/fsevents/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/fsevents/node_modules/node-pre-gyp
npm WARN rm not removing /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/babel-generator/node_modules/.bin/jsesc as it wasn't installed by /Users/zack/Desktop/DERS/react-native-xmpp-demo-master/UnknownCaller/node_modules/babel-generator/node_modules/jsesc
npm notice created a lockfile as package-lock.json. You should commit this file.
+ ansi-styles@3.2.1
removed 1527 packages and updated 1 package in 16.105s
~~~

**Comment by DaveLombardo** [comment]
Here is what I did and it works after:

```
npm install -g expo-cli
expo init AwesomeProject
cd AwesomeProject
npm install    ;this one is missed in RN guide
npm install connectycube-reactnative --save
cd node_modules/connectycube-reactnative/xmpp.js
make
cd ../../../
cp -r node_modules/connectycube-reactnative/xmpp.js/node_modules/* node_modules/
```

than added the following to App.js: 
```
import {ConnectyCube} from 'connectycube-reactnative';
var CB = new ConnectyCube();
```

then started
`npm start`

**Comment by zek** [comment]
I just removed node completely. Installed again and this is works.

Sorry for taking your time.

It works now :) Thank you

**Comment by DaveLombardo** [comment]
@zek  no worries, great to hear it!
In a case of anything else - please raise a separate issue. 
Cheers 👍

**Comment by DaveLombardo** [comment]
Version 1.4.1 is available
https://www.npmjs.com/package/connectycube-reactnative

it's based on xmpp.js 0.5.2 and now you do not need to do any extra work, just do:

`npm install connectycube-reactnative --save`

**Comment by zek** [comment]
Awesome. Thanks 👍

I will try it soon
